export const GET_TOP_ARTISTS_REQUEST = "GET_TOP_ARTISTS_REQUEST";
export const GET_TOP_ARTISTS_SUCCESS = "GET_TOP_ARTISTS_SUCCESS";
export const GET_TOP_ARTISTS_FAIL = "GET_TOP_ARTISTS_FAIL";

export const GET_ARTIST_REQUEST = "GET_ARTIST_REQUEST";
export const GET_ARTIST_SUCCESS = "GET_ARTIST_SUCCESS";
export const GET_ARTIST_FAIL = "GET_ARTIST_FAIL";

export const GET_ALBUM_REQUEST = "GET_ALBUM_REQUEST";
export const GET_ALBUM_SUCCESS = "GET_ALBUM_SUCCESS";
export const GET_ALBUM_FAIL = "GET_ALBUM_FAIL";
